import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:unh_rideshare_app/models/car_model.dart';
import 'package:unh_rideshare_app/models/ride_model.dart';

final mockRide = RideModel(
  rideId: 'ride23',
  driverId: 'driver23',
  vehicleId: 'vehicle23',
  departureDate: '2024-10-08',
  departureTime: '04:30 PM',
  totalSeats: 4,
  availableSeats: 1,
  routeDetails: 'Manchester to Durham',
  status: 'active',
  cancelReason: '',
  cancelledAt: null,
  createdTime: Timestamp.fromDate(
    DateTime.now().subtract(const Duration(days: 23)),
  ),
  vehicle: CarModel(
    vehicleId: 'vehicle23',
    make: 'Pontiac',
    model: 'Grand Prix',
    year: '2018',
    color: 'Silver',
    licensePlate: 'IJK123',
    isComplete: true,
    seats: 4,
  ),
);

final List<RideModel> mockCanceledRides = [
  RideModel(
    rideId: 'cancel1',
    driverId: 'driver23',
    vehicleId: 'vehicle23',
    departureDate: '2024-10-05',
    departureTime: '07:45 AM',
    totalSeats: 4,
    availableSeats: 4,
    routeDetails: 'Durham to Manchester',
    status: 'canceled',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(const Duration(days: 5)),
    ),
    vehicle: CarModel(
      vehicleId: 'vehicle23',
      make: 'Pontiac',
      model: 'Grand Prix',
      year: '2018',
      color: 'Silver',
      licensePlate: 'IJK123',
      isComplete: true,
      seats: 4,
    ),
  ),
  RideModel(
    rideId: 'cancel2',
    driverId: 'driver31',
    vehicleId: 'vehicle31',
    departureDate: '2024-10-06',
    departureTime: '12:10 PM',
    totalSeats: 5,
    availableSeats: 5,
    routeDetails: 'Manchester to Durham',
    status: 'canceled',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(const Duration(days: 4)),
    ),
    vehicle: CarModel(
      vehicleId: 'vehicle31',
      make: 'Honda',
      model: 'Accord',
      year: '2020',
      color: 'White',
      licensePlate: 'QRS221',
      isComplete: true,
      seats: 5,
    ),
  ),
  RideModel(
    rideId: 'cancel3',
    driverId: 'driver44',
    vehicleId: 'vehicle44',
    departureDate: '2024-10-07',
    departureTime: '06:00 PM',
    totalSeats: 4,
    availableSeats: 4,
    routeDetails: 'Durham to Manchester',
    status: 'canceled',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(const Duration(days: 3)),
    ),
    vehicle: CarModel(
      vehicleId: 'vehicle44',
      make: 'Nissan',
      model: 'Sentra',
      year: '2019',
      color: 'Blue',
      licensePlate: 'LMT908',
      isComplete: true,
      seats: 4,
    ),
  ),
];

// Mock list of passenger ride requests (active and canceled rides).
final List<RideModel> mockMyRideRequests = [
  mockRide,
  RideModel(
    rideId: 'ride24',
    driverId: 'driver24',
    vehicleId: 'vehicle24',
    departureDate: '2024-10-09',
    departureTime: '08:00 AM',
    totalSeats: 4,
    availableSeats: 2,
    routeDetails: 'Durham to Manchester',
    status: 'active',
    cancelReason: '',
    cancelledAt: null,
    createdTime: mockRide.createdTime,
    vehicle: mockRide.vehicle,
    enrolledUserIds: const ['passenger_a'],
  ),
  RideModel(
    rideId: 'ride25',
    driverId: 'driver25',
    vehicleId: 'vehicle25',
    departureDate: '2024-10-10',
    departureTime: '06:15 PM',
    totalSeats: 4,
    availableSeats: 1,
    routeDetails: 'Manchester to Durham',
    status: 'active',
    cancelReason: '',
    cancelledAt: null,
    createdTime: mockRide.createdTime,
    vehicle: mockRide.vehicle,
    enrolledUserIds: const ['passenger_b'],
  ),
  RideModel(
    rideId: 'ride26',
    driverId: 'driver26',
    vehicleId: 'vehicle26',
    departureDate: '2024-10-11',
    departureTime: '09:45 AM',
    totalSeats: 4,
    availableSeats: 2,
    routeDetails: 'Durham to Portsmouth',
    status: 'active',
    cancelReason: '',
    cancelledAt: null,
    createdTime: mockRide.createdTime,
    vehicle: mockRide.vehicle,
    enrolledUserIds: const ['passenger_c'],
  ),
  RideModel(
    rideId: 'ride27',
    driverId: 'driver27',
    vehicleId: 'vehicle27',
    departureDate: '2024-10-12',
    departureTime: '05:20 PM',
    totalSeats: 4,
    availableSeats: 3,
    routeDetails: 'Manchester to Concord',
    status: 'active',
    cancelReason: '',
    cancelledAt: null,
    createdTime: mockRide.createdTime,
    vehicle: mockRide.vehicle,
    enrolledUserIds: const ['passenger_d'],
  ),
  ...mockCanceledRides,
];

// Mock placeholder for passenger request statuses by ride ID.
final Map<String, String> mockPassengerRequestStatusByRideId = {
  'ride23': 'pending',
  'ride24': 'accepted',
  'ride25': 'declined',
  'ride26': 'rejected',
  'ride27': 'rejected',
};
