import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:unh_rideshare_app/models/car_model.dart';
import 'package:unh_rideshare_app/models/ride_model.dart';

final List<RideModel> mockAvailableRides = [
  RideModel(
    rideId: 'ride1',
    driverId: 'driver1',
    vehicleId: 'vehicle1',
    departureDate: '2024-10-01',
    departureTime: '08:00 AM',
    totalSeats: 4,
    availableSeats: 3,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(DateTime.now().subtract(Duration(days: 1))),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle1',
      make: 'Toyota',
      model: 'Camry',
      year: '2020',
      color: 'Blue',
      licensePlate: 'ABC123',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride2',
    driverId: 'driver2',
    vehicleId: 'vehicle2',
    departureDate: '2024-10-01',
    departureTime: '09:30 AM',
    totalSeats: 4,
    availableSeats: 2,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(DateTime.now().subtract(Duration(days: 2))),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle2',
      make: 'Honda',
      model: 'Civic',
      year: '2019',
      color: 'Red',
      licensePlate: 'XYZ789',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride3',
    driverId: 'driver3',
    vehicleId: 'vehicle3',
    departureDate: '2024-10-01',
    departureTime: '10:00 AM',
    totalSeats: 4,
    availableSeats: 1,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(DateTime.now().subtract(Duration(days: 3))),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle3',
      make: 'Ford',
      model: 'Focus',
      year: '2018',
      color: 'Black',
      licensePlate: 'LMN456',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride4',
    driverId: 'driver4',
    vehicleId: 'vehicle4',
    departureDate: '2024-10-02',
    departureTime: '11:00 AM',
    totalSeats: 4,
    availableSeats: 2,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(DateTime.now().subtract(Duration(days: 4))),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle4',
      make: 'Chevrolet',
      model: 'Malibu',
      year: '2021',
      color: 'White',
      licensePlate: 'DEF456',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride5',
    driverId: 'driver5',
    vehicleId: 'vehicle5',
    departureDate: '2024-10-02',
    departureTime: '12:30 PM',
    totalSeats: 5,
    availableSeats: 4,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(DateTime.now().subtract(Duration(days: 5))),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle5',
      make: 'Nissan',
      model: 'Altima',
      year: '2022',
      color: 'Silver',
      licensePlate: 'GHI789',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride6',
    driverId: 'driver6',
    vehicleId: 'vehicle6',
    departureDate: '2024-10-02',
    departureTime: '01:00 PM',
    totalSeats: 4,
    availableSeats: 3,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(DateTime.now().subtract(Duration(days: 6))),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle6',
      make: 'Hyundai',
      model: 'Elantra',
      year: '2021',
      color: 'Gray',
      licensePlate: 'JKL012',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride7',
    driverId: 'driver7',
    vehicleId: 'vehicle7',
    departureDate: '2024-10-03',
    departureTime: '02:15 PM',
    totalSeats: 6,
    availableSeats: 2,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(DateTime.now().subtract(Duration(days: 7))),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle7',
      make: 'Kia',
      model: 'Optima',
      year: '2020',
      color: 'Blue',
      licensePlate: 'MNO345',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride8',
    driverId: 'driver8',
    vehicleId: 'vehicle8',
    departureDate: '2024-10-03',
    departureTime: '03:45 PM',
    totalSeats: 4,
    availableSeats: 1,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(DateTime.now().subtract(Duration(days: 8))),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle8',
      make: 'Volkswagen',
      model: 'Jetta',
      year: '2019',
      color: 'White',
      licensePlate: 'PQR678',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride9',
    driverId: 'driver9',
    vehicleId: 'vehicle9',
    departureDate: '2024-10-03',
    departureTime: '04:30 PM',
    totalSeats: 4,
    availableSeats: 2,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(DateTime.now().subtract(Duration(days: 9))),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle9',
      make: 'Mazda',
      model: 'Mazda3',
      year: '2021',
      color: 'Red',
      licensePlate: 'STU901',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride10',
    driverId: 'driver10',
    vehicleId: 'vehicle10',
    departureDate: '2024-10-04',
    departureTime: '07:00 AM',
    totalSeats: 5,
    availableSeats: 3,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 10)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle10',
      make: 'Subaru',
      model: 'Impreza',
      year: '2020',
      color: 'Black',
      licensePlate: 'VWX234',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride11',
    driverId: 'driver11',
    vehicleId: 'vehicle11',
    departureDate: '2024-10-04',
    departureTime: '08:30 AM',
    totalSeats: 4,
    availableSeats: 2,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 11)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle11',
      make: 'BMW',
      model: '3 Series',
      year: '2022',
      color: 'Silver',
      licensePlate: 'YZA567',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride12',
    driverId: 'driver12',
    vehicleId: 'vehicle12',
    departureDate: '2024-10-04',
    departureTime: '10:00 AM',
    totalSeats: 4,
    availableSeats: 4,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 12)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle12',
      make: 'Audi',
      model: 'A4',
      year: '2021',
      color: 'Gray',
      licensePlate: 'BCD890',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride13',
    driverId: 'driver13',
    vehicleId: 'vehicle13',
    departureDate: '2024-10-05',
    departureTime: '11:30 AM',
    totalSeats: 6,
    availableSeats: 1,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 13)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle13',
      make: 'Mercedes-Benz',
      model: 'C-Class',
      year: '2022',
      color: 'Blue',
      licensePlate: 'EFG123',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride14',
    driverId: 'driver14',
    vehicleId: 'vehicle14',
    departureDate: '2024-10-05',
    departureTime: '01:00 PM',
    totalSeats: 5,
    availableSeats: 3,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 14)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle14',
      make: 'Lexus',
      model: 'ES',
      year: '2021',
      color: 'White',
      licensePlate: 'HIJ456',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride15',
    driverId: 'driver15',
    vehicleId: 'vehicle15',
    departureDate: '2024-10-05',
    departureTime: '02:30 PM',
    totalSeats: 4,
    availableSeats: 2,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 15)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle15',
      make: 'Acura',
      model: 'TLX',
      year: '2020',
      color: 'Red',
      licensePlate: 'KLM789',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride16',
    driverId: 'driver16',
    vehicleId: 'vehicle16',
    departureDate: '2024-10-06',
    departureTime: '06:00 AM',
    totalSeats: 4,
    availableSeats: 3,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 16)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle16',
      make: 'Genesis',
      model: 'G70',
      year: '2022',
      color: 'Black',
      licensePlate: 'NOP012',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride17',
    driverId: 'driver17',
    vehicleId: 'vehicle17',
    departureDate: '2024-10-06',
    departureTime: '07:15 AM',
    totalSeats: 5,
    availableSeats: 2,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 17)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle17',
      make: 'Infiniti',
      model: 'Q50',
      year: '2021',
      color: 'Silver',
      licensePlate: 'QRS345',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride18',
    driverId: 'driver18',
    vehicleId: 'vehicle18',
    departureDate: '2024-10-06',
    departureTime: '09:00 AM',
    totalSeats: 4,
    availableSeats: 1,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 18)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle18',
      make: 'Cadillac',
      model: 'CTS',
      year: '2020',
      color: 'Gray',
      licensePlate: 'TUV678',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride19',
    driverId: 'driver19',
    vehicleId: 'vehicle19',
    departureDate: '2024-10-07',
    departureTime: '10:30 AM',
    totalSeats: 6,
    availableSeats: 4,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 19)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle19',
      make: 'Lincoln',
      model: 'MKZ',
      year: '2021',
      color: 'Blue',
      licensePlate: 'WXY901',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride20',
    driverId: 'driver20',
    vehicleId: 'vehicle20',
    departureDate: '2024-10-07',
    departureTime: '12:00 PM',
    totalSeats: 5,
    availableSeats: 3,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 20)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle20',
      make: 'Buick',
      model: 'Regal',
      year: '2020',
      color: 'White',
      licensePlate: 'ZAB234',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride21',
    driverId: 'driver21',
    vehicleId: 'vehicle21',
    departureDate: '2024-10-07',
    departureTime: '01:30 PM',
    totalSeats: 4,
    availableSeats: 2,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 21)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle21',
      make: 'GMC',
      model: 'Acadia',
      year: '2022',
      color: 'Red',
      licensePlate: 'CDE567',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride22',
    driverId: 'driver22',
    vehicleId: 'vehicle22',
    departureDate: '2024-10-08',
    departureTime: '03:00 PM',
    totalSeats: 5,
    availableSeats: 4,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 22)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle22',
      make: 'Saturn',
      model: 'Aura',
      year: '2019',
      color: 'Black',
      licensePlate: 'FGH890',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride23',
    driverId: 'driver23',
    vehicleId: 'vehicle23',
    departureDate: '2024-10-08',
    departureTime: '04:30 PM',
    totalSeats: 4,
    availableSeats: 1,
    routeDetails: 'Manchester to Durham',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 23)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle23',
      make: 'Pontiac',
      model: 'Grand Prix',
      year: '2018',
      color: 'Silver',
      licensePlate: 'IJK123',
      isComplete: true,
    ),
  ),
  RideModel(
    rideId: 'ride24',
    driverId: 'driver24',
    vehicleId: 'vehicle24',
    departureDate: '2024-10-08',
    departureTime: '05:45 PM',
    totalSeats: 6,
    availableSeats: 3,
    routeDetails: 'Durham to Manchester',
    status: 'available',
    createdTime: Timestamp.fromDate(
      DateTime.now().subtract(Duration(days: 24)),
    ),
    cancelReason: '',
    cancelledAt: null,
    vehicle: CarModel(
      vehicleId: 'vehicle24',
      make: 'Oldsmobile',
      model: 'Alero',
      year: '2017',
      color: 'Gray',
      licensePlate: 'LMN456',
      isComplete: true,
    ),
  ),
];
