// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByGpyZORfDswfDZ0oiENCcGhnw0fpHFOU',
    appId: '1:652273195634:android:f556ecbc026fdfc92f80eb',
    messagingSenderId: '652273195634',
    projectId: 'unh-rideshare-app',
    storageBucket: 'unh-rideshare-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7WRPF4wqmgvAuUq06rhxA1kzJowog5lI',
    appId: '1:652273195634:ios:0f3e821a05cb77b72f80eb',
    messagingSenderId: '652273195634',
    projectId: 'unh-rideshare-app',
    storageBucket: 'unh-rideshare-app.firebasestorage.app',
    iosBundleId: 'edu.unh.afive.rideshare',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-PU_h9chjDTIonDYsvKRJdYcG--RUu4',
    appId: '1:652273195634:web:c2ae157ec8f6117a2f80eb',
    messagingSenderId: '652273195634',
    projectId: 'unh-rideshare-app',
    authDomain: 'unh-rideshare-app.firebaseapp.com',
    storageBucket: 'unh-rideshare-app.firebasestorage.app',
  );

}